import { StorefrontFilter, StorefrontProduct } from '../models/storefront-demo.models';

export const featuredProducts: StorefrontProduct[] = [
  {
    slug: 'wine-kanjivaram-silk-saree',
    name: 'Wine Kanjivaram Silk Saree',
    category: 'Silk Sarees',
    sareeType: 'Kanjivaram',
    fabric: 'Pure silk',
    colour: 'Wine',
    pattern: 'Temple border',
    occasion: 'Wedding',
    priceInPaise: 1299900,
    mrpInPaise: 1599900,
    discount: 19,
    rating: 4.8,
    reviews: 126,
    stock: 'Only a few left',
    imageTone: 'wine',
    colours: ['#7a1f32', '#b98b2d', '#4c254f'],
  },
  {
    slug: 'ivory-chanderi-party-saree',
    name: 'Ivory Chanderi Party Saree',
    category: 'Designer Sarees',
    sareeType: 'Chanderi',
    fabric: 'Chanderi silk',
    colour: 'Ivory',
    pattern: 'Floral woven',
    occasion: 'Festive',
    priceInPaise: 749900,
    mrpInPaise: 949900,
    discount: 21,
    rating: 4.7,
    reviews: 84,
    stock: 'In stock',
    imageTone: 'ivory',
    colours: ['#fffaf1', '#d9b45d', '#7a1f32'],
  },
  {
    slug: 'plum-georgette-embroidered-saree',
    name: 'Plum Georgette Embroidered Saree',
    category: 'Party Wear',
    sareeType: 'Georgette',
    fabric: 'Soft georgette',
    colour: 'Plum',
    pattern: 'Zari embroidery',
    occasion: 'Reception',
    priceInPaise: 589900,
    mrpInPaise: 799900,
    discount: 26,
    rating: 4.6,
    reviews: 59,
    stock: 'In stock',
    imageTone: 'plum',
    colours: ['#4c254f', '#8d2c46', '#b98b2d'],
  },
  {
    slug: 'emerald-banarasi-wedding-saree',
    name: 'Emerald Banarasi Wedding Saree',
    category: 'Banarasi Sarees',
    sareeType: 'Banarasi',
    fabric: 'Silk blend',
    colour: 'Emerald',
    pattern: 'Butta weave',
    occasion: 'Wedding',
    priceInPaise: 1099900,
    mrpInPaise: 1399900,
    discount: 21,
    rating: 4.9,
    reviews: 102,
    stock: 'In stock',
    imageTone: 'emerald',
    colours: ['#0d6b57', '#b98b2d', '#fffaf1'],
  },
];

export const storefrontFilters: StorefrontFilter[] = [
  { label: 'Category', values: ['Silk Sarees', 'Banarasi Sarees', 'Designer Sarees', 'Party Wear'] },
  { label: 'Fabric', values: ['Pure silk', 'Chanderi silk', 'Soft georgette', 'Cotton silk'] },
  { label: 'Colour', values: ['Wine', 'Ivory', 'Plum', 'Emerald', 'Maroon'] },
  { label: 'Size', values: ['5.5 m saree', '6.3 m with blouse', 'Free size'] },
  { label: 'Occasion', values: ['Wedding', 'Festive', 'Reception', 'Office', 'Daily wear'] },
  { label: 'Price', values: ['Under Rs. 5,000', 'Rs. 5,000 - Rs. 10,000', 'Above Rs. 10,000'] },
  { label: 'Pattern', values: ['Temple border', 'Floral woven', 'Zari embroidery', 'Butta weave'] },
  { label: 'Discount', values: ['10% and above', '20% and above', '30% and above'] },
  { label: 'Availability', values: ['In stock', 'Only a few left', 'COD available'] },
];

export function formatPrice(paise: number): string {
  return new Intl.NumberFormat('en-IN', {
    currency: 'INR',
    maximumFractionDigits: 0,
    style: 'currency',
  }).format(paise / 100);
}
